[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_BACKEND_URL = "https://surakshabot-health-assistant.onrender.com"
  VITE_GEMINI_API_KEY = "AIzaSyAcOQbsxkZnTC4e6oUvsqpMEBdLlpsHHRo"
  VITE_GOOGLE_MAPS_API_KEY = "AIzaSyBj1GTiBxiND2NJ-QHQySMRTFMXDqCI5ug"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"