[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_BACKEND_URL = "https://surakshabot-health-assistant.onrender.com"
  VITE_GEMINI_API_KEY = "AIzaSyAcOQbsxkZnTC4e6oUvsqpMEBdLlpsHHRo"
  VITE_GOOGLE_MAPS_API_KEY = "AIzaSyBj1GTiBxiND2NJ-QHQySMRTFMXDqCI5ug"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://surakshabot-health-assistant.onrender.com https://generativelanguage.googleapis.com https://maps.googleapis.com; frame-src 'none'; object-src 'none';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"